---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: component-status
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      v: vars.verbosity
    vars:
    - name: selector
    - name: componentName
  command: hyperalert check_component_status
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: json-path
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
    - name: url
      required: true
    - name: secretName
    - name: warning
    - name: critical
  command: hyperalert check_json_path
  state:
  - OK
  - Warning
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: node-exists
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      v: vars.verbosity
    vars:
    - name: selector
    - name: nodeName
    - name: count
  command: hyperalert check_node_exists
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: pod-exists
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
    - name: selector
    - name: podName
    - name: count
  command: hyperalert check_pod_exists
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: event
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
    - name: clockSkew
    - name: involvedObjectName
    - name: involvedObjectNamespace
    - name: involvedObjectKind
    - name: involvedObjectUID
  command: hyperalert check_event
  state:
  - OK
  - Warning
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: ca-cert
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      v: vars.verbosity
    vars:
    - name: warning
    - name: critical
  command: hyperalert check_ca_cert
  state:
  - OK
  - Warning
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: cert
spec:
  alertKinds:
  - ClusterAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
    - name: selector
    - name: secretName
    - name: secretKey
    - name: warning
    - name: critical
  command: hyperalert check_cert
  state:
  - OK
  - Warning
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: node-status
spec:
  alertKinds:
  - NodeAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
  command: hyperalert check_node_status
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: node-volume
spec:
  alertKinds:
  - NodeAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
    - name: mountPoint
      required: true
    - name: secretName
    - name: warning
    - name: critical
  command: hyperalert check_volume
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: pod-status
spec:
  alertKinds:
  - PodAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
  command: hyperalert check_pod_status
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: pod-volume
spec:
  alertKinds:
  - PodAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
    - name: volumeName
      required: true
    - name: secretName
    - name: warning
    - name: critical
  command: hyperalert check_volume
  state:
  - OK
  - Critical
  - Unknown
---
apiVersion: monitoring.appscode.com/v1alpha1
kind: SearchlightPlugin
metadata:
  creationTimestamp: null
  name: pod-exec
spec:
  alertKinds:
  - PodAlert
  arguments:
    host:
      host: name
      v: vars.verbosity
    vars:
    - name: container
    - name: cmd
    - name: argv
      required: true
  command: hyperalert check_pod_exec
  state:
  - OK
  - Critical
  - Unknown
